xgds_sample/urls.py
#__BEGIN_LICENSE__
# Copyright (c) 2015, United States Government, as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All rights reserved.
#
# The xGDS platform is licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#__END_LICENSE__

from django.conf.urls import url, include
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from xgds_sample import views


urlpatterns = [url(r'labels$', views.getSampleLabelsPage, {}, 'xgds_sample_labels'),
               url(r'deleteLabel/(?P<labelNum>[\d]+)$', views.deleteLabelAndSample, {}, 'xgds_sample_delete_label'),
               url(r'edit/sample$', views.getSampleEditPage, {}, 'xgds_sample_record_edit'),
               url(r'edit/sample/(?P<samplePK>[\d]+)$', views.getSampleEditPage, {}, 'xgds_sample_record_edit'), 
               url(r'saveSample$', views.saveSampleInfo, {}, 'xgds_sample_info_save'),
               url(r'labels/print$', views.printSampleLabels, {}, 'xgds_sample_labels_print'),
               url(r'help$', views.getSampleHelpPage, {}, 'xgds_sample_help'),
               # url(r'^search/$', RedirectView.as_view(url=reverse_lazy('search_map_object', kwargs={'modelName':'Sample'}), permanent=False), name='xgds_sample_fullsearch'),
#               url(r'^search/$', RedirectView.as_view(url=reverse('search_map_object'), permanent=False), {'modelName':'Sample'},  'xgds_sample_fullsearch'),
               
               # Including these in this order ensures that reverse will return the non-rest urls for use in our server
               url(r'^rest/', include('xgds_sample.restUrls')),
               url('', include('xgds_sample.restUrls')),

               ]

xgds_sample/forms.py
#__BEGIN_LICENSE__
# Copyright (c) 2015, United States Government, as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All rights reserved.
#
# The xGDS platform is licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#__END_LICENSE__

import datetime
import pytz

from dal import autocomplete

from django.utils import timezone
from django.conf import settings
from django import forms
from django.utils.functional import lazy
from django.contrib.auth.models import User

from django.forms import ModelForm, CharField
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.db.models import Q

from geocamUtil.loader import getModelByName
from xgds_map_server.models import Place
from xgds_sample.models import SampleType, Label
from geocamUtil.loader import LazyGetModelByName
from geocamUtil.forms.AbstractImportForm import getTimezoneChoices

from geocamTrack.utils import getClosestPosition
from geocamUtil.models import SiteFrame
from geocamUtil.TimeUtil import utcToLocalTime
from xgds_core.forms import SearchForm
from xgds_core.flightUtils import lookup_vehicle

LOCATION_MODEL = LazyGetModelByName(settings.GEOCAM_TRACK_PAST_POSITION_MODEL)
SAMPLE_MODEL = LazyGetModelByName(settings.XGDS_SAMPLE_SAMPLE_MODEL)
XGDS_CORE_VEHICLE_MODEL = LazyGetModelByName(settings.XGDS_CORE_VEHICLE_MODEL)
PLACE_FILTER_URL = '/xgds_core/complete/%s.json/' % 'xgds_map_server.Place'

class CollectorCharField(CharField):
    def label_from_instance(self, obj):
        return "TEST LABEL"


class SampleForm(ModelForm):
    lat = forms.FloatField(required=False, label="Latitude")
    lon = forms.FloatField(required=False, label="Longitude")
    altitude = forms.FloatField(required=False, label="Altitude")
    description = forms.CharField(widget=forms.Textarea, required=False, label="Description")
    collector_name = forms.CharField(required=False, label="Collector")
    name = forms.CharField(widget = forms.HiddenInput(), required = False, label="Name", help_text='Name autofills on save.')
    
    hidden_labelNum = forms.IntegerField(widget = forms.HiddenInput(), required = False)
    hidden_name = forms.CharField(widget = forms.HiddenInput(), required = False)
    pk = forms.IntegerField(widget = forms.HiddenInput(), required = False)
    
    collection_time = forms.DateTimeField(required=True, input_formats=settings.XGDS_CORE_DATE_FORMATS, help_text="")
    collection_timezone = forms.CharField(widget=forms.HiddenInput(), initial=settings.TIME_ZONE)
    
    field_order = SAMPLE_MODEL.get().getFieldOrder()
    
    def __init__(self, *args, **kwargs):
        super(SampleForm, self).__init__(*args, **kwargs)
        self.fields['pk'].initial = self.instance.pk
        if self.instance.collector:
            self.fields['collector_name'].initial = self.instance.collector.first_name + ' ' + self.instance.collector.last_name
        positionDict = self.instance.getPositionDict()
        self.fields['lat'].initial = positionDict['lat']
        self.fields['lon'].initial = positionDict['lon']
        if 'altitude' in positionDict:
            self.fields['altitude'].initial = positionDict['altitude']
        if 'depth' in positionDict:
            self.fields['depth'].initial = positionDict['depth']
        if settings.XGDS_MAP_SERVER_DEFAULT_PLACE_ID:
            self.fields['place'].initial = Place.objects.get(id=settings.XGDS_MAP_SERVER_DEFAULT_PLACE_ID)
        self.fields['place'].empty_label = None
        if self.instance.collection_time:
            utc_collection_time = self.instance.collection_time
        else: 
            utc_collection_time = timezone.now()
        local_time = utcToLocalTime(utc_collection_time) 
        collection_time = local_time.strftime("%m/%d/%Y %H:%M:%S")
        self.initial['collection_time'] = collection_time
    
    def clean_year(self):
        year = self.cleaned_data['year']
        if year == None:
            raise forms.ValidationError(u"You haven't set a year.")
        return year
    
    def clean_collection_timezone(self):
        try:
            return self.cleaned_data['collection_timezone']
        except:
            return settings.TIME_ZONE

    def clean_collection_time(self): 
        ctime = self.cleaned_data['collection_time']
        if ctime:  # if there is a time input, convert to utc
            ctimezone = self.clean_collection_timezone()
            tz = pytz.timezone(ctimezone)
            naiveTime = ctime.replace(tzinfo = None)
            localizedTime = tz.localize(naiveTime)
            utcTime = localizedTime.astimezone(pytz.utc)
            ctime = utcTime
        return ctime

    def clean(self):
        """
        Checks that both lat and lon are entered (or both are empty)
        Checks that collection time is entered if user is entering position for the first time.
        """
        cleaned_data = super(SampleForm, self).clean()
        lat = cleaned_data.get("lat")
        lon = cleaned_data.get("lon")
        if (lat and not lon) or (not lat and lon):  # if only one of them is filled in
            msg = "Must enter both latitude and longitude or leave both blank."
            self.add_error('lat', msg)
            self.add_error('lon', msg)
        if lat and lon:
            instance = super(SampleForm, self).save(commit=False)
            if instance.user_position is None:
                if not self.cleaned_data['collection_time']:
                    msg = "Must enter collection time to record position"
                    self.add_error('collection_time', msg)

    def save(self, commit=True):
        instance = super(SampleForm, self).save(commit=False)
        instance.collection_time = self.cleaned_data['collection_time']
        if instance.vehicle_name and instance.collection_time:
            instance.track_position = getClosestPosition(timestamp=instance.collection_time, vehicle=lookup_vehicle(instance.vehicle_name))
            
        if (('lat' in self.changed_data) and ('lon' in self.changed_data)) or 'altitude' in self.changed_data or 'depth' in self.changed_data:
            if instance.user_position is None:
                instance.user_position = LOCATION_MODEL.get().objects.create(serverTimestamp=datetime.datetime.now(pytz.utc),
                                                                             timestamp=instance.collection_time,
                                                                             latitude=self.cleaned_data['lat'],
                                                                             longitude=self.cleaned_data['lon'],
                                                                             altitude=self.cleaned_data['altitude'],
                                                                             depth=self.cleaned_data['depth'])
            else:
                instance.user_position.latitude = self.cleaned_data['lat']
                instance.user_position.longitude = self.cleaned_data['lon']
                instance.user_position.altitude = self.cleaned_data['altitude']
                instance.user_position.depth = self.cleaned_data['depth']

        if 'collector_name' in self.changed_data:
            fullName = self.cleaned_data['collector_name']
            try: 
                splitName = fullName.split(' ')
                firstAndLast = [x for x in splitName if x.strip()]
                collector = User.objects.filter(first_name=firstAndLast[0]).filter(last_name=firstAndLast[1])[0] 
                instance.collector = collector
            except: 
                self.errors['error'] = "Save Failed. User %s does not exist." % fullName
                return instance
        
        # if fields changed, validate against the name
        needsNameRebuild = False
        for field in SAMPLE_MODEL.get().getFieldsForName():
            if field in self.changed_data:
                needsNameRebuild = True
                break
        if needsNameRebuild:
            builtName = instance.buildName()
            if instance.name != builtName:
                instance.name = builtName 
        if commit:
            instance.save()
        return instance

    class Meta: 
        model = getModelByName(settings.XGDS_SAMPLE_SAMPLE_MODEL)
        exclude = ['track_position', 
                   'user_position', 
                   'creation_time', 
                   'modification_time', 
                   'creator', 
                   'modifier', 
                   'collector',
                   'label']


class SearchSampleForm(SearchForm):
    place = forms.ModelChoiceField(Place.objects.all(),
                                   label=settings.XGDS_MAP_SERVER_PLACE_MONIKER,
                                   required=False,
                                   widget=autocomplete.ModelSelect2(url=PLACE_FILTER_URL))

    sample_type = forms.ModelChoiceField(required=False, queryset=SampleType.objects.all())
    label = forms.IntegerField(required=False)
    
    min_collection_time = forms.DateTimeField(input_formats=settings.XGDS_CORE_DATE_FORMATS, required=False, label='Min Time',
                                              widget=forms.DateTimeInput(attrs={'class': 'datetimepicker'}))
    max_collection_time = forms.DateTimeField(input_formats=settings.XGDS_CORE_DATE_FORMATS, required=False, label = 'Max Time',

xgds_sample/templates/xgds_sample/sampleEdit.html
{% extends 'xgds_sample/sampleEdit_base.html' %}

xgds_sample/templates/xgds_sample/sampleEditForm.html
{% extends 'dashboard_base.html' %}

{% block sitemenu-content-secondary %}
	{% include "sample_subnav.html" %}
    {% load nav %}
{% endblock %}

 {% block cssExtras %}
 {{ block.super }}
 {% include "xgds_notes2/NoteCSS.html" %}
  <link rel="stylesheet" type="text/css" href="{{ EXTERNAL_URL }}jqueryui-timepicker-addon/dist/jquery-ui-timepicker-addon.css"></link>
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}xgds_sample/css/xgds_sample.css"></link>
 {% endblock cssExtras %}


{% block scripts %}
{{block.super}}
	{% include "xgds_notes2/NoteJS.html" %}
	<script type="text/javascript" src='{{ EXTERNAL_URL }}/handlebars/handlebars.min.js'></script>
	{% include "xgds_core/timeJS.html" %}
	<script language="javascript" type="text/javascript" src="{{ EXTERNAL_URL }}jqueryui-timepicker-addon/dist/jquery-ui-timepicker-addon.min.js"></script>
	<script type="text/javascript" src='{{ STATIC_URL }}xgds_core/js/datetimepickerUtils.js'></script>
	<script type="text/javascript" src='{{ STATIC_URL }}xgds_sample/js/sampleReview.js'></script>
	
    <!--  load handlebars -->
	{% for template_name, template in templates.items %}
		<script type="text/handlebars" id="template-{{template_name}}">
			{{template|safe}}
		</script>
	{% endfor %}
{% endblock scripts %}

{% block jsInit %} 
{{ block.super }}
addDateTimePicker("id_collection_time", $('#id_collection_timezone').val());

// initialize the notes when the window is ready
$(document).ready(function() {
	// hook position editing to set flag
	hookEditingPosition($('#updateSampleForm'));
	
	// show existing notes
	var container = $('#notes_content');
	var tbl = container.find('table#notes_list');
	initializeNotesReference(container, '{{form.instance.modelAppLabel}}', '{{form.instance.modelTypeName}}', '{{form.instance.pk }}', '{{form.instance.collection_time|date:"Y-m-d H:i:s"}}' + ' UTC', '{{form.instance.collection_timezone}}');
	getNotesForObject('{{form.instance.modelAppLabel}}', '{{form.instance.modelTypeName}}', '{{form.instance.pk }}', 'notes_content', tbl);

	// show the notes div
	var notes_input_div = $("#notes_input");
	notes_input_div.removeAttr('hidden');
	notes_input_div.show();
	
    initializeTags();
    var taginput = container.find('.taginput');
	initializeInput($(taginput)[0]);
 	hookNoteSubmit();

 	
});
{% endblock jsInit %} 


{% load xgds_sample_extras %}

{% block firstPackery %} 
<div class='item w2 lockAspect' id='item_sample_create' data-isStamped="false">
	<i class="icon-lock-open pinDiv"></i>
	<div class="error-message upload-error"></div>
	<div id="save-status"> {{status}} </div>
	
	{% if messages %}
	<div id="messages">
  		{% for message in messages %}
    	<p>{{ message }}</p>
    	{% endfor %}
	</div>
	{% endif %}
	<div><strong> Editing sample </strong></div>
	
	<form class="updateSample" id="updateSampleForm" action="{% url 'xgds_sample_record_update' form.instance.label.number %}" method="post" enctype="multipart/form-data">
		<input type=hidden name=sampleId value="{{ form.instance.pk }}">
		{% for hidden in form.hidden_fields %}
		{{ hidden }}
		{% endfor %}
		<table>
			<tr>
				<th><label for="id_label_number">Label Number:</label></th>
				<td><input id="id_label_number" maxlength="512" name="labelNum" type="text" value="{{ form.instance.label.number }}" readonly /></td>
			</tr>
			<tr class="sample_name_row">
				<th><label for="id_name">Name:</label></th>
				<td><input id="id_name" maxlength="512" name="name" type="text" placeholder="i.e NC16B001A" value="{{ form.instance.name }}"/></td>
			</tr>
			{{ form.as_table }}
		</table>
		{% csrf_token %}
		<div id="sample-edit-button-group">
		<a href="recordSample" class="mybutton small">Cancel</a>
		<input class="mybutton small" id="sample-info-submit" type="submit" value="Save"/>
		</div>
	</form>
	<br><hr>
	<div id="complete_notes">
		<strong>Notes</strong>
		<div id="notes_content" class="tab-content active">
		{% include 'xgds_notes2/notes_input_include.html' %}
		{% include 'xgds_notes2/notes_table_small.html' %}
		</div>
	</div>
</div>
{{ block.super }}
{% endblock firstPackery %}

xgds_sample/templates/xgds_sample/sampleEdit_base.html
{% extends 'dashboard_base.html' %}

{% load json_dumps %}
{% load static %}

{% block sitemenu-content-secondary %}
	{% include "sample_subnav.html" %}
    {% load nav %}
{% endblock %}
{% block siteSection %}Sample Edit{% endblock %}

 {% block cssExtras %}
 {{ block.super }}
 {% include "xgds_notes2/NoteCSS.html" %}
  <link rel="stylesheet" type="text/css" href="{{ EXTERNAL_URL }}jquery-ui-timepicker-addon/dist/jquery-ui-timepicker-addon.css"></link>
  <link rel="stylesheet" type="text/css" href="{% static 'xgds_sample/css/xgds_sample.css' %}"></link>
 {% endblock cssExtras %}


{% block scripts %}
{{block.super}}
	{% include "xgds_notes2/NoteJS.html" %}
	<script type="text/javascript" src='{{ EXTERNAL_URL }}/handlebars/dist/handlebars.min.js'></script>
	<script type="text/javascript" src="{{ EXTERNAL_URL }}typeahead.js/dist/typeahead.bundle.min.js"></script> 
	<script type="text/javascript" src="{{ EXTERNAL_URL }}jquery-ui-timepicker-addon/dist/jquery-ui-timepicker-addon.min.js"></script>
	<script type="text/javascript" src="{% static 'xgds_core/js/datetimepickerUtils.js' %}"></script>
	<script type="text/javascript" src="{% static 'xgds_sample/js/sampleEdit.js' %}"></script>
	<script type="text/javascript">
		var collectors = {{ users|safe }};
	</script>
	
    <!--  load handlebars -->
	{% for template_name, template in templates.items %}
		<script type="text/handlebars" id="template-{{template_name}}">
			{{template|safe}}
		</script>
	{% endfor %}
{% endblock scripts %}

{% block jsInit %} 
{{ block.super }}
// url to server side code that fetches sample info for given sample label or name.
var getSampleInfoUrl = '{{ getSampleInfoUrl }}';
var sampleJson = undefined;
{% if form.instance.pk %}
var sampleJson = {{ sampleMapDict|safe}}[0];
var hiddenLabel = "{{form.instance.label_number}}";
var hiddenName = "{{form.instance.name}}";
{% else %}
var hiddenLabel = null;
var hiddenName = null;
{% endif %}

var fieldsEnabledFlag = {{ fieldsEnabledFlag }};

// add time picker 
addDateTimePicker("id_collection_time", $('#id_collection_timezone').val());

// initialize the notes when the window is ready
$(document).ready(function() {
	{% if form.instance %}
		var thedata = [{{form.instance.toMapDict|json_dumps|safe}}];
		showOnMap([{{form.instance.toMapDict|json_dumps|safe}}]);
		
		// show existing notes
		var container = $('#notes_content');
		xgds_notes.setupNotesUI(container);
		xgds_notes.initializeNotesReference(container, '{{form.instance.app_label}}', '{{form.instance.model_type}}', '{{form.instance.pk }}', '{{form.instance.collection_time|date:"Y-m-d H:i:s"}}' + ' UTC', '{{form.instance.collection_timezone}}');
		xgds_notes.getNotesForObject('{{form.instance.app_label}}', '{{form.instance.model_type}}', '{{form.instance.pk }}', 'notes_content', container.find('table.notes_list'));
	{% endif %}

	xgds_sample.initializeSampleEditForm();
});
{% endblock jsInit %} 


{% load range %}

{% block preDashboard %}
{% if messages %}
<div class="alert alert-warning" role="alert">
    {% for message in messages %}
    <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span></br>
    {% endfor %}
</div>
{% endif  %}
{% endblock preDashboard %}

{% block preMap %} 
<div class="grid-stack-item" id='item_sample_create'
        data-gs-x="0" data-gs-y="0"
        data-gs-width="3" data-gs-height="5">
            <div class="grid-stack-item-content">
            <ul class="nav justify-content-end">
				<i class="fa fa-lock pinDiv gray-light"></i>
			</ul>
	<div id="error-message" class="mt-negative-1rem"></div>
	<div><strong> Look up sample </strong></div>
	<table id="lookupsample_table" class="form-inline">
		<tr>
			<th>
				<select class="sample_info_type mt-1" id="search_input_type">
					<option value="labelNum">Label Number</option>
					<option value="sampleName">Sample Name</option>
				</select>
			</th>
			<td class='sample_info_type_value form-group'><input id="id_search_input" min="0" />  <button id="load" onclick="xgds_sample.onEnterLoadSampleInfo()" type="button" class="btn btn-primary ml-1">Load</button> </td>
		</tr>
	</table>
	
	<div id="label_number_title"><strong> </strong></div>
	<div id="sample_name_title"><strong> </strong></div>
	{% if form.errors %}
    <ol>
    {% for error in form.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ol>
	{% endif %}
	<form class="updateSample" id="updateSampleForm" action="{% url 'xgds_sample_info_save' %}" method="post" enctype="multipart/form-data">
		<table>
			{{ form.as_table }}
			<tr>
			<td colspan='2'>
			<a id="toggleInputFields" class="btn btn-primary" onclick="xgds_sample.toggleAdvancedInput();" href="#">Show Position</a>
			<input class="btn btn-primary small" id="sample-info-submit" type="submit" value="Save"/>
			</td>
			</tr>
		</table>
		{% csrf_token %}
		
	</form>
	
	<hr>
 	<div id="complete_notes">
		<strong>Notes</strong>
		<div id="notes_content" class="tab-content active notes_content">
		{% include 'xgds_notes2/notes_input_include.html' %}
		{% include 'xgds_notes2/notes_table_small.html' %}
		</div>
	</div> 
	</div>
</div>

{% endblock preMap %}

xgds_sample/templates/xgds_sample/sampleView.html
{% extends 'dashboard_base.html' %}
{% load tz %}
{% load userName %}
{% load static %}
{% load json_dumps %}
{% block sitemenu-content-secondary %}
	{% include "sample_subnav.html" %}
{% endblock %}

 {% block cssExtras %}
 {{ block.super }}
  {% include "xgds_notes2/NoteCSS.html" %}
    <link rel="stylesheet" type="text/css" href="{% static 'xgds_sample/css/xgds_sample.css' %}"></link>
 {% endblock cssExtras %}


{% block scripts %}
{{block.super}}
	{% include "xgds_notes2/NoteJS.html" %}
	<script language="javascript" type="text/javascript" src="{{ EXTERNAL_URL }}jquery-ui-timepicker-addon/dist/jquery-ui-timepicker-addon.min.js"></script>
{% endblock scripts %}

{% block otherJSInit %} 

// initialize the notes when the window is ready
	{% if sample %}
		showOnMap([{{sample.toMapDict|json_dumps|safe}}]);
	{% endif %}
	
	var container = $('#notes_content');
	xgds_notes.setupNotesUI();
	xgds_notes.initializeNotesReference(container, '{{sample.app_label}}', '{{sample.model_type}}', '{{sample.pk }}', '{{sample.collection_time|date:"Y-m-d H:i:s"}}' + ' UTC', '{{sample.collection_timezone}}');
	xgds_notes.getNotesForObject('{{sample.app_label}}', '{{sample.model_type}}', '{{sample.pk }}', 'notes_content', container.find('table.notes_list'));

{% endblock otherJSInit %} 

{% block preDashboard %} 
{% if messages %}
        <div id="messages">
	  		{% for message in messages %}
	    	<p>{{ message }}</p>
	    	{% endfor %}
		</div>
</div>
{% endif %}
{% endblock preDashboard %}

{% block preMap %}
<div class="grid-stack-item" id='item_sample_create'
        data-gs-x="0" data-gs-y="0"
        data-gs-width="3" data-gs-height="4">
        <div class="grid-stack-item-content" >
	<div class="error-message upload-error"></div>
	<ul class="nav justify-content-end">
		<i class="fa fa-unlock-alt pinDiv gray-light"></i><br />
	</ul>
	<div id="save-status" class="mt-negative-1rem"> {{status}} </div>
	
	<div> <strong> Viewing sample</strong> <a id="edit_sample_button" href="{% url 'xgds_sample_record_update' sample.label.number %}" class="btn btn-primary small">Edit</a> </div>
	<input type=hidden name=sampleId value="{{ sample.pk }}">
	<table>
		<tr>
			<th><label for="id_name">Name:</label></th>
			<td> {{ sample.name }}</td>
		</tr>
		<tr>
			<th><label for="id_type">Type:</label></th>
			<td> {{ sample.sample_type.display_name }}</td>
		</tr>
		<tr>
			<th><label for="id_place">{{settings.XGDS_MAP_SERVER_PLACE_MONIKER}}:</label></th>
			<td>{{ sample.place.name }}</td>
		</tr>
		<tr>
			<th><label for="id_vehicle">Vehicle:</label></th>
			<td>{{ sample.vehicle.name }}</td>
		</tr>
		<tr>
			<th><label for="id_collector">Collector:</label></th>
			<td>{% userName sample.collector %}</td>
		</tr>
		<tr>
			<th><label for="id_number">Number:</label></th>
			<td>{{ sample.number }}</td>
		</tr>
		<tr>
			<th><label for="id_latitude">Latitude:</label></th>
			<td>{{ sample.user_position.latitude }}</td>
		</tr>
		<tr>
			<th><label for="id_longitude">Longitude:</label></th>
			<td>{{ sample.user_position.longitude }}</td>
		</tr>
		<tr>
			<th><label for="id_altitude">Altitude:</label></th>
			<td>{{ sample.user_position.altitude }}</td>
		</tr>
		<tr>
			<th><label for="id_collection_time">Collection time:</label></th>
			<td>{% timezone sample.collection_timezone %}{{ sample.collection_time|date:"Y-m-d H:i e" }}{% endtimezone %}</td>
		</tr>
		<tr>
			<th><label for="id_description">Description:</label></th>
			<td>{{ sample.description }}</td>
		</tr>
	</table>
	<hr/>
	<div id="complete_notes">
		<strong>Notes</strong>
		<div id="notes_content" class="tab-content active notes_content">
		{% include 'xgds_notes2/notes_input_include.html' %}
		{% include 'xgds_notes2/notes_table_small.html' %}
		</div>
	</div>
	{% csrf_token %}	
	</div>
</div>

{% endblock preMap %}

{% block postMap %}
<div class="grid-stack-item noresize" id='create_sample_from_label_num'
        data-gs-x="3" data-gs-y="3"
        data-gs-width="2" data-gs-height="1">
        <div class="grid-stack-item-content" >
        <ul class="nav justify-content-end">
			<i class="fa fa-unlock-alt pinDiv gray-light"></i>
		</ul>
		<form class="label_number_form mt-negative-1rem" id="label_number_form" action="{% url 'xgds_sample_record_edit' %}" method="post" enctype="multipart/form-data">
			<strong> Look up sample </strong>
			<table>
				<tr>
					<th><label for="id_label_number">Label # or sample name:</label></th>
					<td><input id="id_label_number" maxlength="512" name="label_num_or_sample_name" type="text" /></td>
				</tr>
			</table>
			{% csrf_token %}
			<input id="record_sample_submit_btn btn-primary" type="submit" class="small" value="Open"/> 
		</form>
	</div>
</div>
{% endblock postMap %}